#SPDX-License-Identifier: MIT-0
---
# tasks file for docker

- name: Install Require Packages
  ansible.builtin.apt:
    name: "{{ system_require_packages }}"
    update_cache: true
    state: present

- name: Add Docker GPG apt Key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: Add Docker Repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: true

- name: Update apt and Install Docker-ce
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "{{ dockers_pkg }}"

- name: Install Docker Module for Python
  ansible.builtin.apt:
    name: python3-docker
    state: present

- name: Start and Enable Docker
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true
  notify:
    - "Restart Docker"

- name: Add User in Group Docker
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"


